### ISSUE TITLE
Pasting code to the repl

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-lang#183] opened 2021-01-20 21:58 UTC
If I copy multiple forms at once into the REPL only the first form is evaluated.

Example:

Copy the code:
```
(+ 1 1)
(+ 2 2)
```

Paste it into the REPL. Output looks like this:
```
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> (+ 1 1)
(+ 2 2)
2
>>> 
```

The behavior in other REPLs is different. The expected output should look like this:
```
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> (+ 1 1)
2
>>> (+ 2 2)
```

All expression, except the last, are evaluated. The last expression needs to be evaluated by clicking enter. If that behavior is not possible I would at least expect that every expression is evaluated.

**Comment by Chemaclass** [comment] 2021-01-21 07:23
I cannot reproduce this issue? What I am doing is:
1)  `php phel repl`

2) copy-paste the example that you provide in the issue
```
(+ 1 1)
(+ 2 2)
```

3) Current behavior:
```
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> (+ 1 1)
2
>>> (+ 2 2)
```

As I understood from the issue description is that the expected behavior is actually what I am seeing from the current behavior (?). Can you please double-check this? I tried this in docker and local.

**Comment by JesusValera** [comment] 2021-01-21 08:49
Works well for me too 👍🏼

**Comment by jenshaase** [comment] 2021-01-21 19:17
Interesting. Didn't work for me that way.

**Comment by Chemaclass** [comment] 2021-01-21 20:02
But does it work for you now? Did you tested locally and inside docker? 🤔

**Comment by jenshaase** [comment] 2021-01-21 20:25
No in docker it didn't work at all. It looks like this:
```
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> 0~(+ 1 1)
Can not resolve symbol '0~'
in string:1

1| 0~
   ^^
>>> (+ 2 2)1~
```

It adds bad symbols like `0~` and `1~`

**Comment by mabasic** [comment] 2021-01-21 20:27
Sometimes I also get symbols like `0~` and `1~` after pasting code. Using Windows Terminal or VS Code integrated terminal. Need to try on Linux to verify the same behavior.

**Comment by jenshaase** [comment] 2021-01-21 20:35
@Chemaclass @JesusValera What do you get when you paste something like this:

```
(+
 1
 1)
```

My result is this (after pressing enter):
```
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> (+
 1
 1)
2
>>>
```

**Comment by Chemaclass** [comment] 2021-01-21 20:43
@jenshaase, my result is this error:
```clojure
Welcome to the Phel Repl
Type "exit" or press Ctrl-D to exit.
>>> (+
Unterminated list
in string:1

1| (+
   ^^
>>>  1
nil
>>>  1)
```

**Comment by jenshaase** [comment] 2021-01-21 20:53
Ok, I think it mainly depends on how the PHP extension `readline` is build. There are two ways to build this library.

1. Based on GNU Readline
2. Based on Libedit

You can can check the version with this PHP command:
```php
\readline_info('library_version');
```
On my machine the version info shows `8.0` (which probably mean GNU Readline 8.0). In the docker container the version info is `EditLine wrapper` (which probably is libedit).

What are your versions?

**Comment by Chemaclass** [comment] 2021-01-21 20:58
```php
php > var_dump(\readline_info());
php shell code:1:
array(6) {
  'line_buffer' =>
  string(28) "var_dump(\readline_info());
"
  'point' =>
  int(0)
  'end' =>
  int(0)
  'library_version' =>
  string(16) "EditLine wrapper"
  'readline_name' =>
  string(0) ""
  'attempted_completion_over' =>
  int(0)
}
php > 
```

**Comment by mabasic** [comment] 2021-01-21 22:57
> (+
>  1
>  1)

Windows Terminal:

```
>>> (+
 1)Unterminated list
in string:1

1| (+
   ^^
>>>  1
nil
>>>  1)
nil
>>>
```

VS Code integrated terminal:

```
>>> 0~(+
Can not resolve symbol '0~'
in string:1

1| 0~
   ^^
>>> 1
1
>>> 1)1~
1
>>> 
```

I remember Laravel tinker/artisan having a similar issue few years ago, regarding `0~` and similar artifacts... can't remember how they have solved it.

**Comment by jenshaase** [comment] 2021-01-22 07:34
Hi,

tinker/artisan is based on Psysh. I tried psysh myself and could reproduce the same `~0/~1` problem in der Docker container. There is an issue that discusses that problem: https://github.com/bobthecow/psysh/issues/636
It doesn't looks like there is good solution currently (except from building PHP with GNU Readline instead of libedit).

**Comment by Chemaclass** [comment] 2021-05-25 06:51
Is this issue still relevant? Or should we close it? cc: @jenshaase

**Closed** 2021-05-25 18:24 UTC
Labels: bug
