### ISSUE TITLE
Cannot run php code generated with build

### ISSUE THREAD

**Issue by bentxt** [phel-lang/phel-lang#606] opened 2023-06-21 11:56 UTC
I had made a ticket few month ago, which was closed by now: https://github.com/phel-lang/phel-lang/issues/589

The ticket was closed after a alternative solution was given. The solution is legitimate, but I still have the problem, that I cannot run the generated php code with the `build` command

https://phel-lang.org/documentation/cli-commands/

```
Build
Compile the current project into the out-dir folder. This means that the compiled phel code into PHP will be saved in that directory, so you can run the PHP code directly using the PHP interpreter. This will improve the runtime performance, because there won't be a need to compile the code again.
```

But it doesn't work a
```
 vendor/bin/phel  build
php out/cli_skeleton/main.php

[...]/phel/cli-skeleton/out/phel/core.php:3
Stack trace:
[...]/phel/cli-skeleton/out/cli_skeleton/main.php(3): require_once()
#1 {main}
  thrown in [...]/phel/cli-skeleton/out/phel/core.php on line 3
```

**Comment by Chemaclass** [comment] 2023-06-21 12:37
The issue is that the current main.php that we generate when running the `phel build` command is missing the autoload from vendor, therefore it doesn't know where to find the dependency classes. E.g:
```
Uncaught Error: Class "Phel\Lang\Registry" not found in ./temp/cli-skeleton/out/phel/core.php:3
```

An alternative solution for now: you can create a script yourself similar to what I did here: https://github.com/Chemaclass/phel-snake/blob/main/play.php
```php
<?php declare(strict_types=1);

require_once __DIR__ . "/vendor/autoload.php";

$compiledFile = __DIR__ . "/out/phel_snake/main.php";
if (!file_exists($compiledFile)) {
    echo 'Building the project...';
    exec('vendor/bin/phel build --no-cache');
}

require_once $compiledFile;
```

With this script you are requiring the `vendor/autoload` file and then calling your "main built entry point".

--- 
That said, this is an interesting observation that might need a rethink to avoid this work around all the time, and rather be something integrated as part of the "build" command. Therefore, we can agree that this is not a bug, but a "feature" that I will take a deeper look. Thanks for reporting it, @bentxt !

**Comment by Chemaclass** [comment] 2023-06-22 08:39
@bentxt I created a PR (https://github.com/phel-lang/phel-lang/pull/607) automating the creation of this template, so this will be part of the build command.

**Comment by Chemaclass** [comment] 2023-06-23 13:51
Already merged in the main branch. Here you have a demo:

https://github.com/phel-lang/phel-lang/assets/5256287/1177fc8f-85e2-440e-a7ba-f79fa75229be

**Closed** 2023-06-23 13:51 UTC
Labels: enhancement
